### ISSUE TITLE
Clear-up Domain ownership verification

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/say-yes-to-https#10]
In #7, @MacLemon said

> [We should remove the] part with the domain ownership verification by CAs since they actually don't do that. Ownership of a domain is not a requirement for the issuance of a certificate for a hostname under that domain.

**Comment by ericandrewlewis** [comment]
@MacLemon, do you have any examples of CAs that don't do this? Wouldn't this invalidate the utility of a CA, if they don't do any validation?

**Comment by MacLemon** [comment]
I'll not get into the discussion of how useful CAs are in general. I guess we all agree that there are huge amounts of problems with CAs in general.

Regarding domain **ownership**: No CA does this for Class 1 Domain validated certificates from my experience. If you can somehow make plausible that you have some sort of vague control over the domain you usually can get a certificate.
Most CAs will either do a mail ping to some contact listed in the whois. That only proves that you can access that email in some way. That might be some sysadmin, executive, or your ISP or registrar, or email admin, or someone who has access to the ticket system where it arrives.

Some CAs require you to host a one-time-token in a well known path on the hostname you're requesting the cert for on port 80. If you can put that token on the webserver, they'll accept that.

“Having control” over a domain/hostname is a broad term and does not imply any legal ownership.

Some CAs may do more in depth checks for Class 2 and Class 3 certs, at least they should. Same goes for extended validation snake oil.

**Comment by ericandrewlewis** [comment]
So it sounds like the term "control" is more true to form than "ownership," even if its still a broad term. Do you think changing the wording here would be an improvement? e.g.

> A site owner requests a certificate from a certificate authority (CA) for a domain. The CA will confirm the person has control over the domain, and then issues a certificate.

**Comment by MacLemon** [comment]
“Control” is as broad as it can be, and most CAs don't actually confirm that you actually have control as I said. Sometimes having access to the mail ping is enough, you don't even have to be able to access a webserver at all.

The whole sentence is **extremely** simplifying the process. It so much depends on the CA, the type of certificate (DV, wildcard, EV, Class type, domain, etc.), your reputation with the CA, the top level domain…

What about:

> A site owner sends a **certificate signing request** for a hostname to a CA. Most CAs will perform some sort of verification that you have control over that domain and, upon success, issue a certificate.

**Comment by ericandrewlewis** [comment]
> The whole sentence is extremely simplifying the process.

It is a goal of this project to summarize the mechanics HTTPS for web developers to understand without exposing them to complex jargon that may not be critical for the basic concepts. Of course, balancing this with technical precision is just as important :smile: 

> Sometimes having access to the mail ping is enough, you don't even have to be able to access a webserver at all.

I'm not sure what you mean by mail ping. The experience I've had with SSLMate is they'll send an email to a WHOIS contact email of my choice. I'll then click an authorization link in the email. It sounds like a mail ping is different from this? Does it not prove that you have access to a WHOIS email account?

> What about:
> 
> > A site owner sends a certificate signing request for a hostname to a CA. Most CAs will perform some sort of verification that you have control over that domain and, upon success, issue a certificate.

If possible, I'd like to avoid speaking about CSRs at this level. Services like SSLMate and Let's Encrypt obscure this step from the user, so it would be extra information that not every web developer will need to know.

**Comment by MacLemon** [comment]
What SSLMate does is commonly called a mail-ping. :-) There are a lot of emails in WHOIS information, not all of which are under the control of the domain proprietor. ISPs and registrars also are listed in WHOIS and, for example, StartSSL will happily send pings there. Also, anyone having access to the email server where any of those emails arrive can “klick that link”. This system actually doesn't verify control over the hostname.domain.tld at all, it verifies that someone can read an email.

There are other validation methods, like making a CA generated and signed token available on a well-known path on the webserver that shall use the certificate. This is a lot better and actually checks that you have control over the webserver for that hostname. This is essentially what the let's encrypt client tries to do, which still needs a lot of improvement, but that is a totally different story.

I wouldn't remove the CSR at all, since it is a very necessary step. It would be fine to tell people that **some tools** automate the steps of creating a CSR and sending it to a CA for you. Most of the ones I had to deal with don't. Also keep in mind that CAs not only issue certs for webservers but all kinds of services, like XMPP, Email servers, Code signing, client authentication, etc.

**Comment by ericandrewlewis** [comment]
I think "control" is an okay word to use without getting overly technical.

If you have access to an email server for a domain, or if you can edit files on the server a domain points to, that constitutes control to me.

I've updated the text in 167b76010310c96303f11a1e93b38cf2f8bd9ba6 to

> A site owner requests a certificate from a certificate authority, or CA, for a domain. The CA confirms the person has control over the domain (through various means), and then issues a certificate.

This also implies a CSR without explicitly naming it, using basic language where possible. 

Thanks for bringing this up, closing this out. Hopefully this is a good balance between technical accuracy and ease of read.
