### ISSUE TITLE
"SSL certificate" is a misnomer

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/say-yes-to-https#8]
@MacLemon suggested in #7 

> [We should] replace occurrences of “SSL” with TLS since all versions of SSL are cryptographically and technically broken in practice. SSL should never be used at all anymore, hence the usage of the correct term “TLS” is highly encouraged.

This is a sticky problem. Many CAs still use the term "SSL certificate," I assume because of brand identity.

Let's Encrypt refers to TLS certificates as just "certificates." I like this approach.

**Comment by mholt** [comment]
Just my $0.02: I always understood TLS as a wrapper over SSL; i.e. the "SSL certificate" is still for the benefit of a _secure socket layer_, but these days they are used by programs that implement TLS.

**Comment by MacLemon** [comment]
SSL is not a wrapper over SSL in any technical means.

Why I more or less insist on calling TLS the proper name of TLS is that any webdev who wants to implement SSL, will probably actually do implement SSLv2 or SSLv3 all of which are horrendously broken and insecure. Labels do matter, which is why I consider it important to name things correctly.

I like the Let's encrypt approach of just calling them certificates. Makes text also more readable.

**Comment by ericandrewlewis** [comment]
> any webdev who wants to implement SSL, will probably actually do implement SSLv2 or SSLv3 all of which are horrendously broken and insecure. 

This sounds like a separate and very valid issue that we should address. In [this section](https://sayyestohttps.org/how-to-setup-https/#serve-http-and-https) there's a link to Mozilla's config generator, which suggests some very broad levels of configuration compatibility (modern, intermediate, old). We can probably expand on this to lead developers to implement as strong a crypto setup as they can for the clients they need to support.

I've opened #16 to dig into that.
